import http from 'node:http';
import { DatabaseSync } from 'node:sqlite';
import { randomUUID, randomBytes, createHash, scrypt, timingSafeEqual } from 'node:crypto';
import { mkdirSync } from 'node:fs';
import { readFile } from 'node:fs/promises';
import { resolve, dirname, extname, sep } from 'node:path';
import { pathToFileURL } from 'node:url';
import { promisify } from 'node:util';
import { createContentService, serializeContentError } from './content.mjs';
import { createAiSearchService, serializeAiSearchError } from './ai-search.mjs';
import { createWechatReminderService } from './wechat-reminders.mjs';
const fail=(status,message)=>{throw Object.assign(new Error(message),{status})};
const hash=v=>createHash('sha256').update(v).digest('hex');
const scryptAsync=promisify(scrypt);
const APP_TERMS_VERSION='2026-09-22';
const normalizeAppUsername=value=>String(value||'').trim().toLowerCase();
const validAppUsername=value=>/^[a-z0-9][a-z0-9_.-]{3,31}$/.test(value);
const validAppPassword=value=>typeof value==='string'&&value.length>=8&&value.length<=128;
async function derivePassword(password,salt){return Buffer.from(await scryptAsync(password,salt,64)).toString('hex')}
async function passwordMatches(password,credential){const actual=Buffer.from(await derivePassword(password,credential.salt),'hex');const expected=Buffer.from(credential.password_hash,'hex');return actual.length===expected.length&&timingSafeEqual(actual,expected)}
export function createApp({dbPath='server/data/app.sqlite',testAuth=false,wxAppId='',wxSecret='',wxReminderTemplateId='SRj7mQ0c6juhTrXsl8VRWLpLJuwehMjZpWRNUlar1ts',publicDir='',fetchImpl=globalThis.fetch,contentConfig={},aiConfig={},appRegistrationCode=''}={}){
 mkdirSync(dirname(resolve(dbPath)),{recursive:true});const db=new DatabaseSync(dbPath);
 db.exec(`PRAGMA journal_mode=WAL; CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY, identity TEXT UNIQUE,nickname TEXT,couple TEXT); CREATE TABLE IF NOT EXISTS app_credentials(user TEXT PRIMARY KEY,username TEXT UNIQUE,password_hash TEXT NOT NULL,salt TEXT NOT NULL,terms_version TEXT NOT NULL,created_at INTEGER NOT NULL); CREATE TABLE IF NOT EXISTS sessions(token TEXT PRIMARY KEY,user TEXT,expires INTEGER); CREATE TABLE IF NOT EXISTS invites(code TEXT PRIMARY KEY,owner TEXT,expires INTEGER,used INTEGER DEFAULT 0); CREATE TABLE IF NOT EXISTS items(id TEXT PRIMARY KEY,owner TEXT,couple TEXT,kind TEXT,data TEXT); CREATE TABLE IF NOT EXISTS item_shares(token TEXT PRIMARY KEY,item TEXT,owner TEXT,created_at INTEGER,expires INTEGER,revoked INTEGER DEFAULT 0); CREATE TABLE IF NOT EXISTS files(id TEXT PRIMARY KEY,owner TEXT,name TEXT,bytes BLOB); CREATE TABLE IF NOT EXISTS notifications(id TEXT PRIMARY KEY,user TEXT,title TEXT,due TEXT,seen INTEGER DEFAULT 0); CREATE TABLE IF NOT EXISTS wechat_reminder_subscriptions(id TEXT PRIMARY KEY,item TEXT,user TEXT,due TEXT,status TEXT,created_at INTEGER,sent_at INTEGER,error TEXT); CREATE INDEX IF NOT EXISTS idx_item_shares_item ON item_shares(item,revoked,expires); CREATE INDEX IF NOT EXISTS idx_wechat_reminder_due ON wechat_reminder_subscriptions(status,due); CREATE INDEX IF NOT EXISTS idx_app_credentials_username ON app_credentials(username);`);
 db.exec("UPDATE wechat_reminder_subscriptions SET status='pending' WHERE status='sending'");
 const content=createContentService({db,dbPath,fetchImpl,...contentConfig});
 const ai=createAiSearchService({fetchImpl,...aiConfig});
 const wechatReminders=createWechatReminderService({appId:wxAppId,secret:wxSecret,templateId:wxReminderTemplateId,fetchImpl,timeZone:aiConfig.timeZone||'Asia/Shanghai'});
 const one=(s,...a)=>db.prepare(s).get(...a); const all=(s,...a)=>db.prepare(s).all(...a);const run=(s,...a)=>db.prepare(s).run(...a);
 const transaction=fn=>{db.exec('BEGIN IMMEDIATE');try{const r=fn();db.exec('COMMIT');return r}catch(e){db.exec('ROLLBACK');throw e}};
 const publicUser=u=>({id:u.id,nickname:u.nickname,partner:u.couple?all('SELECT id,nickname FROM users WHERE couple=? AND id<>?',u.couple,u.id)[0]||null:null});
 const publicRoot=publicDir?resolve(publicDir):'';const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8','.png':'image/png','.svg':'image/svg+xml','.ico':'image/x-icon','.woff2':'font/woff2'};
 async function servePublic(req,res,pathname){if(!publicRoot||!['GET','HEAD'].includes(req.method))return false;let decoded;try{decoded=decodeURIComponent(pathname)}catch{return false}const relative=(decoded==='/'?'index.html':decoded.replace(/^\/+/,''));let file=resolve(publicRoot,relative);if(file!==publicRoot&&!file.startsWith(publicRoot+sep))return false;try{let bytes=await readFile(file);res.writeHead(200,{'Content-Type':mime[extname(file).toLowerCase()]||'application/octet-stream','Cache-Control':extname(file)==='.html'?'no-cache':'public, max-age=31536000, immutable','X-Content-Type-Options':'nosniff','Referrer-Policy':'same-origin'});if(req.method==='HEAD')return res.end();res.end(bytes);return true}catch{if(extname(relative))return false;file=resolve(publicRoot,'index.html');try{const bytes=await readFile(file);res.writeHead(200,{'Content-Type':mime['.html'],'Cache-Control':'no-cache','X-Content-Type-Options':'nosniff','Referrer-Policy':'same-origin'});if(req.method==='HEAD')return res.end();res.end(bytes);return true}catch{return false}}}
 const issueSession=u=>{const token=randomBytes(32).toString('hex');run('INSERT INTO sessions VALUES(?,?,?)',hash(token),u.id,Date.now()+30*864e5);return {token,user:publicUser(u)}};
 const registrationCode=String(appRegistrationCode||'').trim();
 const registrationCodeMatches=value=>{const expected=Buffer.from(hash(registrationCode));const actual=Buffer.from(hash(String(value||'').trim()));return timingSafeEqual(actual,expected)};
 const session=identity=>{let u=one('SELECT * FROM users WHERE identity=?',identity);if(!u){const id=randomUUID();run('INSERT INTO users VALUES(?,?,?,NULL)',id,identity,identity.startsWith('test:')?identity.slice(5):'新朋友');u=one('SELECT * FROM users WHERE id=?',id)}return issueSession(u)};
 const authFailures=new Map();
 const authFailureKey=username=>username||'invalid';
 const assertAppAuthAvailable=username=>{const state=authFailures.get(authFailureKey(username));if(!state)return;if(state.resetAt<=Date.now()){authFailures.delete(authFailureKey(username));return}if(state.count>=8)fail(429,'尝试次数过多，请 15 分钟后再试')};
 const recordAppAuthFailure=username=>{const key=authFailureKey(username),now=Date.now(),state=authFailures.get(key);authFailures.set(key,!state||state.resetAt<=now?{count:1,resetAt:now+15*60*1000}:{...state,count:state.count+1})};
 const clearAppAuthFailures=username=>authFailures.delete(authFailureKey(username));
 const visible=(item,u)=>item.owner===u.id||Boolean(item.couple&&item.couple===u.couple);
 const visibleItems=u=>all('SELECT * FROM items WHERE owner=? OR (? IS NOT NULL AND couple=?)',u.id,u.couple,u.couple);
 const searchDocuments=(u,searchScope)=>{
 const documents=visibleItems(u).map(item=>{try{const value=JSON.parse(item.data);return {id:item.id,type:item.kind,title:value.title,content:value.content,updatedAt:value.updatedAt,nextAt:value.nextAt,route:`/pages/detail/detail?id=${encodeURIComponent(item.id)}`}}catch{return null}}).filter(Boolean);
 if(searchScope==='notes')return documents;
 if(searchScope==='all'||searchScope==='sports'){
  try{for(const competition of content.getCompetitions().competitions||[]){try{const payload=content.getSports(competition.id);for(const match of payload.matches||[])documents.push({id:`sports:${match.id}`,type:'sports',title:`${match.home?.name||match.home?.shortName||'主队'} vs ${match.away?.name||match.away?.shortName||'客队'}`,content:[competition.name,match.stage,match.status,match.score?.home!=null?`${match.score.home}:${match.score.away}`:'',match.venue].filter(Boolean).join(' · '),updatedAt:payload.meta?.updatedAt,nextAt:match.startsAt,route:`/pages/match-detail/match-detail?id=${encodeURIComponent(match.id)}`})}catch{}}}catch{}
 }
 if(searchScope==='all'||searchScope==='news'){
  const seen=new Set();for(const channel of ['featured','market','hot']){try{const payload=content.getNews(channel);for(const story of payload.stories||[]){if(seen.has(story.id))continue;seen.add(story.id);documents.push({id:`news:${story.id}`,type:'news',title:story.title,content:[story.summary,story.content,story.source,...(story.tags||[])].filter(Boolean).join(' · '),updatedAt:story.publishedAt,route:`/pages/news-detail/news-detail?id=${encodeURIComponent(story.id)}`})}}catch{}}
 }
 return documents;
 };
 const pendingWechatDeliveries=new Set();
 const reminderUsers=(item,d)=>{const owner=one('SELECT * FROM users WHERE id=?',item.owner);if(d.recipient==='me')return owner?[owner]:[];return all('SELECT * FROM users WHERE couple=?',item.couple).filter(u=>d.recipient==='both'||u.id!==owner?.id)};
 const openidFor=user=>{const prefix=`wx:${wxAppId}:`;return String(user?.identity||'').startsWith(prefix)?String(user.identity).slice(prefix.length):''};
 function queueWechatDelivery(delivery){const promise=wechatReminders.send(delivery).then(()=>run("UPDATE wechat_reminder_subscriptions SET status='sent',sent_at=?,error=NULL WHERE id=?",Date.now(),delivery.subscriptionId)).catch(error=>{const code=String(error?.message||'WECHAT_SEND_FAILED').slice(0,160);run("UPDATE wechat_reminder_subscriptions SET status='failed',error=? WHERE id=?",code,delivery.subscriptionId);console.error(JSON.stringify({event:'wechat_reminder_failed',subscriptionId:delivery.subscriptionId,code:code.split(':')[0]}))}).finally(()=>pendingWechatDeliveries.delete(promise));pendingWechatDeliveries.add(promise)}
 async function flushWechat(){await Promise.allSettled([...pendingWechatDeliveries])}
 function tick(now=Date.now()){
  const deliveries=[];transaction(()=>{for(const item of all("SELECT * FROM items WHERE kind='reminder'")){const d=JSON.parse(item.data);if(d.done||Date.parse(d.nextAt)-d.advance*60000>now)continue;const users=reminderUsers(item,d);for(const u of users){run('INSERT OR IGNORE INTO notifications VALUES(?,?,?,?,0)',hash(item.id+':'+u.id+':'+d.nextAt),u.id,d.title,d.nextAt);const subscription=one("SELECT * FROM wechat_reminder_subscriptions WHERE item=? AND user=? AND due=? AND status='pending'",item.id,u.id,d.nextAt);if(subscription){run("UPDATE wechat_reminder_subscriptions SET status='sending',error=NULL WHERE id=?",subscription.id);deliveries.push({subscriptionId:subscription.id,openid:openidFor(u),title:d.title,due:d.nextAt,note:d.content,itemId:item.id})}}if(d.repeat==='none')d.done=true;else{let next=Date.parse(d.nextAt);while(next-d.advance*60000<=now)next+=(d.repeat==='daily'?1:7)*864e5;d.nextAt=new Date(next).toISOString()}run('UPDATE items SET data=? WHERE id=?',JSON.stringify(d),item.id)}});for(const delivery of deliveries)queueWechatDelivery(delivery);return deliveries.length
 }
 const server=http.createServer(async(req,res)=>{const requestId=randomUUID();const send=(status,body,headers={})=>{res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff','Referrer-Policy':'same-origin','X-Request-Id':requestId,...headers});res.end(JSON.stringify(body))};try{
 const url=new URL(req.url,'http://localhost');if(url.pathname.startsWith('/api/media/')){if(await content.serveMedia(req,res,url.pathname))return;return send(404,{message:'图片不存在'})}if(!url.pathname.startsWith('/api')){if(await servePublic(req,res,url.pathname))return;return send(404,{message:'页面不存在'})}const path=url.pathname.slice(4)||'/';
 let size=0;const chunks=[];for await(const chunk of req){size+=chunk.length;if(size>(path==='/files'?12:1)*1024*1024)fail(413,'内容超过大小限制');chunks.push(chunk)}let b={};if(size&&path!=='/files'){try{b=JSON.parse(Buffer.concat(chunks).toString())}catch{fail(400,'请求格式错误')}}
 if(path==='/health')return send(200,{ok:true});
 if(path==='/auth/app/status'&&req.method==='GET')return send(200,{registrationEnabled:Boolean(registrationCode)});
 if(path==='/auth/test'&&req.method==='POST'){if(!testAuth)fail(404,'接口不存在');if(!['我','小金子','访客'].includes(b.name))fail(400,'无效测试账号');return send(200,session('test:'+b.name))}
 if(path==='/auth/wechat'&&req.method==='POST'){if(!wxAppId||!wxSecret)fail(503,'微信登录尚未配置');if(typeof b.code!=='string'||b.code.length>256)fail(400,'登录凭证无效');const query=new URLSearchParams({appid:wxAppId,secret:wxSecret,js_code:b.code,grant_type:'authorization_code'});const wx=await fetchImpl('https://api.weixin.qq.com/sns/jscode2session?'+query,{signal:AbortSignal.timeout(10000)}).then(r=>r.json());if(!wx.openid)fail(401,'微信登录失败，请重试');return send(200,session('wx:'+wxAppId+':'+wx.openid))}
 if(path==='/auth/app/register'&&req.method==='POST'){
  const username=normalizeAppUsername(b.username),password=String(b.password||''),nickname=String(b.nickname||'').trim();
  if(!registrationCode)fail(503,'App 内测注册尚未开放');
  if(!registrationCodeMatches(b.betaCode))fail(403,'内测口令不正确');
  if(!validAppUsername(username))fail(400,'账号请填写 4—32 位小写字母、数字、点、横线或下划线');
  if(!validAppPassword(password))fail(400,'密码请填写 8—128 个字符');
  if(!nickname||nickname.length>20)fail(400,'昵称请填写 1—20 个字');
  if(b.acceptedTerms!==true)fail(400,'请先阅读并同意用户协议与隐私政策');
  if(one('SELECT user FROM app_credentials WHERE username=?',username))fail(409,'这个账号已经注册');
  const salt=randomBytes(16).toString('hex'),passwordHash=await derivePassword(password,salt),id=randomUUID();
  try{transaction(()=>{run('INSERT INTO users VALUES(?,?,?,NULL)',id,'app:'+username,nickname);run('INSERT INTO app_credentials VALUES(?,?,?,?,?,?)',id,username,passwordHash,salt,APP_TERMS_VERSION,Date.now())})}catch(error){if(String(error?.message||'').includes('UNIQUE'))fail(409,'这个账号已经注册');throw error}
  return send(201,issueSession(one('SELECT * FROM users WHERE id=?',id)));
 }
 if(path==='/auth/app/login'&&req.method==='POST'){
  const username=normalizeAppUsername(b.username),password=String(b.password||'');assertAppAuthAvailable(username);
  const credential=validAppUsername(username)&&validAppPassword(password)?one('SELECT * FROM app_credentials WHERE username=?',username):null;
  const comparison=credential||{salt:'00000000000000000000000000000000',password_hash:'00'.repeat(64)};
  const valid=validAppUsername(username)&&validAppPassword(password)&&await passwordMatches(password,comparison);
  if(!valid||!credential){recordAppAuthFailure(username);fail(401,'账号或密码不正确')}
  const accountUser=one('SELECT * FROM users WHERE id=?',credential.user);if(!accountUser){recordAppAuthFailure(username);fail(401,'账号或密码不正确')}
  clearAppAuthFailures(username);return send(200,issueSession(accountUser));
 }
 if(/^\/invites\/[^/]+$/.test(path)&&req.method==='GET'){const code=decodeURIComponent(path.slice('/invites/'.length)).trim().toUpperCase();const i=one('SELECT * FROM invites WHERE code=? AND used=0 AND expires>?',code,Date.now());if(!i)fail(404,'邀请已失效，请让对方重新分享');const owner=one('SELECT * FROM users WHERE id=?',i.owner);if(!owner||owner.couple)fail(410,'邀请已失效，请让对方重新分享');return send(200,{nickname:owner.nickname,expires:i.expires})}
 if(/^\/shared\/items\/[^/]+$/.test(path)&&req.method==='GET'){const sharedToken=path.slice('/shared/items/'.length);if(!/^[a-f0-9]{48}$/.test(sharedToken))fail(404,'分享已失效');const share=one('SELECT * FROM item_shares WHERE token=? AND revoked=0 AND expires>?',sharedToken,Date.now());if(!share)fail(404,'分享已失效');const i=one('SELECT * FROM items WHERE id=?',share.item);if(!i)fail(404,'内容已被删除');const data=JSON.parse(i.data);return send(200,{id:i.id,kind:i.kind,title:data.title,content:data.content||'',scope:'link',pinned:false,links:[],attachments:[],updatedAt:data.updatedAt,nextAt:data.nextAt,repeat:data.repeat,advance:data.advance,done:data.done})}
 const token=(req.headers.authorization||'').replace(/^Bearer /,'');const ses=one('SELECT * FROM sessions WHERE token=? AND expires>?',hash(token),Date.now());if(!ses)fail(401,'请先登录');const user=one('SELECT * FROM users WHERE id=?',ses.user);
 if(path==='/me'&&req.method==='GET')return send(200,publicUser(user));
 if(path==='/me'&&req.method==='PUT'){const nickname=String(b.nickname||'').trim();if(!nickname||nickname.length>20)fail(400,'昵称请填写 1—20 个字');run('UPDATE users SET nickname=? WHERE id=?',nickname,user.id);return send(200,publicUser(one('SELECT * FROM users WHERE id=?',user.id)))}
 if(path==='/me'&&req.method==='DELETE'){
  const credential=one('SELECT * FROM app_credentials WHERE user=?',user.id);if(!credential)fail(400,'当前登录方式暂不支持在 App 内注销');
  const password=String(b.password||'');if(!validAppPassword(password)||!await passwordMatches(password,credential))fail(403,'密码不正确');
  const ownedItems=all('SELECT id FROM items WHERE owner=?',user.id),ownedFiles=new Set(all('SELECT id FROM files WHERE owner=?',user.id).map(file=>file.id)),couple=user.couple;
  transaction(()=>{
   for(const item of ownedItems){run('DELETE FROM item_shares WHERE item=?',item.id);run('DELETE FROM wechat_reminder_subscriptions WHERE item=?',item.id)}
   if(couple){for(const item of all('SELECT id,data FROM items WHERE couple=? AND owner<>?',couple,user.id)){const data=JSON.parse(item.data);if(Array.isArray(data.attachments)){data.attachments=data.attachments.filter(file=>!ownedFiles.has(file.id));run('UPDATE items SET data=? WHERE id=?',JSON.stringify(data),item.id)}}run('UPDATE items SET couple=NULL WHERE couple=?',couple);run('UPDATE users SET couple=NULL WHERE couple=? AND id<>?',couple,user.id)}
   run('DELETE FROM item_shares WHERE owner=?',user.id);run('DELETE FROM items WHERE owner=?',user.id);run('DELETE FROM files WHERE owner=?',user.id);run('DELETE FROM notifications WHERE user=?',user.id);run('DELETE FROM wechat_reminder_subscriptions WHERE user=?',user.id);run('DELETE FROM invites WHERE owner=?',user.id);run('DELETE FROM sessions WHERE user=?',user.id);run('DELETE FROM app_credentials WHERE user=?',user.id);run('DELETE FROM users WHERE id=?',user.id);
  });
  return send(200,{ok:true});
 }
 if(path==='/logout'&&req.method==='POST'){run('DELETE FROM sessions WHERE token=?',hash(token));return send(200,{ok:true})}
 if(path==='/wechat/subscription/status'&&req.method==='GET')return send(200,wechatReminders.status());
 if(path==='/ai/status'&&req.method==='GET')return send(200,ai.status());
 if(path==='/ai/search'&&req.method==='POST'){const result=await ai.search({query:b.query,scope:b.scope,strategy:b.strategy,userId:user.id,documents:searchDocuments(user,b.scope||'all')});if(result.mode==='empty'&&result.fallbackCode)console.warn(JSON.stringify({event:'ai_search_empty',requestId,scope:b.scope||'all',strategy:b.strategy||'smart',fallbackCode:result.fallbackCode}));return send(200,result)}
 if(path==='/content/competitions'&&req.method==='GET')return send(200,content.getCompetitions());
 if(/^\/content\/sports\/matches\/[^/]+$/.test(path)&&req.method==='GET')return send(200,content.getMatch(decodeURIComponent(path.slice('/content/sports/matches/'.length))));
 if(/^\/content\/sports\/[^/]+$/.test(path)&&req.method==='GET')return send(200,content.getSports(decodeURIComponent(path.slice('/content/sports/'.length))));
 if(path==='/content/news'&&req.method==='GET')return send(200,content.getNews(url.searchParams.get('channel')||'featured'));
 if(/^\/content\/news\/[^/]+$/.test(path)&&req.method==='GET')return send(200,content.getNewsStory(decodeURIComponent(path.slice('/content/news/'.length))));
 if(path==='/content/refresh'&&req.method==='POST')return send(200,await content.refresh({target:b.target,competitionId:b.competitionId,channel:b.channel}));
 if(path==='/invite'&&req.method==='POST'){if(user.couple)fail(409,'已经绑定另一半');run('DELETE FROM invites WHERE owner=?',user.id);const code=randomBytes(6).toString('hex').toUpperCase();run('INSERT INTO invites VALUES(?,?,?,0)',code,user.id,Date.now()+864e5);return send(200,{code,expires:Date.now()+864e5})}
 const invite=()=>{const i=one('SELECT * FROM invites WHERE code=? AND used=0 AND expires>?',String(b.code||'').trim().toUpperCase(),Date.now());if(!i)fail(400,'邀请码无效或已过期');if(i.owner===user.id)fail(400,'不能邀请自己');const owner=one('SELECT * FROM users WHERE id=?',i.owner);if(owner.couple||user.couple)fail(409,'其中一方已经绑定');return {i,owner}};
 if(path==='/invite/preview'&&req.method==='POST'){const {owner}=invite();return send(200,{nickname:owner.nickname})}
 if(path==='/invite/accept'&&req.method==='POST'){transaction(()=>{const {i,owner}=invite();const c=randomUUID();run('UPDATE users SET couple=? WHERE id IN (?,?)',c,user.id,owner.id);run('UPDATE invites SET used=1 WHERE code=?',i.code)});return send(200,publicUser(one('SELECT * FROM users WHERE id=?',user.id)))}
 if(path==='/files'&&req.method==='POST'){if(!size)fail(400,'文件不能为空');const name=decodeURIComponent(req.headers['x-file-name']||'附件').slice(0,150);const total=one('SELECT COALESCE(SUM(length(bytes)),0) total FROM files WHERE owner=?',user.id).total;if(total+size>100*1024*1024)fail(413,'附件空间已满（100MB）');const id=randomUUID();run('INSERT INTO files VALUES(?,?,?,?)',id,user.id,name,Buffer.concat(chunks));return send(200,{id,name,size})}
 if(path.startsWith('/files/')&&req.method==='GET'){const file=one('SELECT * FROM files WHERE id=?',path.split('/')[2]);if(!file)fail(404,'文件不存在');const allowed=file.owner===user.id||all('SELECT * FROM items WHERE couple=?',user.couple).some(i=>JSON.parse(i.data).attachments?.some(a=>a.id===file.id));if(!allowed)fail(404,'文件不存在');res.writeHead(200,{'Content-Type':'application/octet-stream','Content-Disposition':"attachment; filename*=UTF-8''"+encodeURIComponent(file.name),'X-Content-Type-Options':'nosniff','Cache-Control':'no-store'});return res.end(Buffer.from(file.bytes))}
 if(path==='/items'&&req.method==='GET'){return send(200,visibleItems(user).map(i=>({...JSON.parse(i.data),id:i.id,owner:i.owner,kind:i.kind,scope:i.couple?'shared':'mine'})))}
 if(/^\/items\/[^/]+$/.test(path)&&req.method==='GET'){const i=one('SELECT * FROM items WHERE id=?',path.split('/')[2]);if(!i||!visible(i,user))fail(404,'内容不存在');return send(200,{...JSON.parse(i.data),id:i.id,owner:i.owner,kind:i.kind,scope:i.couple?'shared':'mine'})}
 if(/^\/items\/[^/]+\/share$/.test(path)&&req.method==='POST'){const id=path.split('/')[2];const i=one('SELECT * FROM items WHERE id=?',id);if(!i||!visible(i,user))fail(404,'内容不存在');let share=one('SELECT token,expires FROM item_shares WHERE item=? AND owner=? AND revoked=0 AND expires>? ORDER BY created_at DESC LIMIT 1',id,user.id,Date.now());if(!share){share={token:randomBytes(24).toString('hex'),expires:Date.now()+30*864e5};run('INSERT INTO item_shares VALUES(?,?,?,?,?,0)',share.token,id,user.id,Date.now(),share.expires)}return send(200,{...share,path:`/pages/detail/detail?share=${share.token}`})}
 if(path==='/items'&&req.method==='POST'||path.startsWith('/items/')&&req.method==='PUT'){
 let existing=null;let id=req.method==='PUT'?path.split('/')[2]:randomUUID();if(req.method==='PUT'){existing=one('SELECT * FROM items WHERE id=?',id);if(!existing||!visible(existing,user))fail(404,'内容不存在');if(existing.owner!==user.id&&b.scope==='mine')fail(403,'只有创建者可以改为私人内容')}
 const kind=existing?.kind||b.kind;if(!['note','reminder'].includes(kind))fail(400,'无效内容类型');const requestedSourceKey=String(b.sourceKey||'').trim();if(requestedSourceKey&&!/^[a-z0-9][a-z0-9:._-]{1,199}$/i.test(requestedSourceKey))fail(400,'无效来源标识');if(req.method==='POST'&&kind==='reminder'&&requestedSourceKey){const duplicate=all("SELECT * FROM items WHERE owner=? AND kind='reminder'",user.id).find(item=>{try{return JSON.parse(item.data).sourceKey===requestedSourceKey}catch{return false}});if(duplicate){existing=duplicate;id=duplicate.id}}const existingData=existing?JSON.parse(existing.data):{};const sourceKey=requestedSourceKey||existingData.sourceKey||'';const title=String(b.title||'').trim();if(!title||title.length>100)fail(400,'标题请填写 1—100 个字');if(!['mine','shared'].includes(b.scope))fail(400,'无效可见范围');if(b.scope==='shared'&&!user.couple)fail(400,'请先绑定另一半');const data={title,content:String(b.content||'').slice(0,50000),updatedAt:new Date().toISOString(),pinned:!!b.pinned,links:Array.isArray(b.links)?b.links.filter(x=>typeof x==='string'&&/^https?:\/\//i.test(x)).slice(0,20):[],...(sourceKey?{sourceKey}:{})};
 data.attachments=[];for(const a of (Array.isArray(b.attachments)?b.attachments:[]).slice(0,10)){const file=one('SELECT id,owner,name,length(bytes) size FROM files WHERE id=?',String(a.id));const old=existing?JSON.parse(existing.data).attachments||[]:[];if(!file||(file.owner!==user.id&&!old.some(x=>x.id===file.id)))fail(403,'无权引用此附件');data.attachments.push({id:file.id,name:file.name,size:file.size})}
 if(kind==='reminder'){if(!['none','daily','weekly'].includes(b.repeat)||!['me','partner','both'].includes(b.recipient))fail(400,'提醒规则无效');if(b.recipient!=='me'&&b.scope!=='shared')fail(400,'提醒另一半需要共享');const time=Date.parse(b.nextAt);if(!Number.isFinite(time))fail(400,'请选择提醒时间');if(!existing&&time<Date.now()-60000)fail(400,'提醒时间不能早于现在');Object.assign(data,{nextAt:new Date(time).toISOString(),repeat:b.repeat,recipient:b.recipient,advance:[0,15,30,60].includes(b.advance)?b.advance:0,done:!!b.done})}
 const owner=existing?.owner||user.id;const itemCouple=b.scope==='shared'?user.couple:null;run('INSERT INTO items VALUES(?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET couple=excluded.couple,data=excluded.data',id,owner,itemCouple,kind,JSON.stringify(data));let wechatSubscribed=false;if(kind==='reminder'){const savedItem={id,owner,couple:itemCouple};const targetIds=new Set(reminderUsers(savedItem,data).map(target=>target.id));for(const subscription of all("SELECT id,user,due FROM wechat_reminder_subscriptions WHERE item=? AND status='pending'",id)){if(!targetIds.has(subscription.user)||subscription.due!==data.nextAt)run("UPDATE wechat_reminder_subscriptions SET status='replaced' WHERE id=?",subscription.id)}if(b.wechatSubscribe===true&&wechatReminders.status().configured&&targetIds.has(user.id)){run("UPDATE wechat_reminder_subscriptions SET status='replaced' WHERE item=? AND user=? AND status IN ('pending','sending')",id,user.id);const subscriptionId=hash(`${id}:${user.id}:${data.nextAt}`);run("INSERT OR REPLACE INTO wechat_reminder_subscriptions VALUES(?,?,?,?,?,?,NULL,NULL)",subscriptionId,id,user.id,data.nextAt,'pending',Date.now());wechatSubscribed=true}}return send(200,{...data,id,owner,kind,scope:b.scope,wechatSubscribed})}
 if(path.startsWith('/items/')&&req.method==='DELETE'){const i=one('SELECT * FROM items WHERE id=?',path.split('/')[2]);if(!i||!visible(i,user))fail(404,'内容不存在');if(i.owner!==user.id)fail(403,'只有创建者可以删除');run('DELETE FROM items WHERE id=?',i.id);run('DELETE FROM item_shares WHERE item=?',i.id);run("UPDATE wechat_reminder_subscriptions SET status='cancelled' WHERE item=? AND status='pending'",i.id);return send(200,{ok:true})}
 if(path==='/notifications'&&req.method==='GET'){tick();return send(200,all('SELECT * FROM notifications WHERE user=? ORDER BY due DESC LIMIT 100',user.id))}
 if(path==='/notifications/read'&&req.method==='POST'){run('UPDATE notifications SET seen=1 WHERE user=?',user.id);return send(200,{ok:true})}
 fail(404,'接口不存在');
 }catch(e){if(e.isContentError){const result=serializeContentError(e,requestId);console.error(JSON.stringify({event:'content_request_failed',requestId,method:req.method,path:req.url,status:result.status,code:result.body.error.code,retryable:result.body.error.retryable}));const headers=Number.isFinite(result.body.error.retryAfterSeconds)?{'Retry-After':String(result.body.error.retryAfterSeconds)}:{};return send(result.status,{message:result.body.error.message,code:result.body.error.code,...result.body},headers)}if(e.isAiSearchError){const result=serializeAiSearchError(e,requestId);console.error(JSON.stringify({event:'ai_search_failed',requestId,method:req.method,path:req.url,status:result.status,code:result.body.error.code,retryable:result.body.error.retryable}));const headers=Number.isFinite(result.body.error.retryAfterSeconds)?{'Retry-After':String(result.body.error.retryAfterSeconds)}:{};return send(result.status,result.body,headers)}send(e.status||500,{message:e.status?e.message:'服务暂时不可用，请稍后重试'})}});
 return {server,db,tick,flushWechat,content,ai,wechatReminders};
}
if(process.argv[1]&&import.meta.url===pathToFileURL(resolve(process.argv[1])).href){const app=createApp({dbPath:process.env.DB_PATH||'server/data/app.sqlite',wxAppId:process.env.WX_APP_ID,wxSecret:process.env.WX_APP_SECRET,wxReminderTemplateId:process.env.WX_REMINDER_TEMPLATE_ID||undefined,publicDir:process.env.PUBLIC_DIR,appRegistrationCode:process.env.APP_REGISTRATION_CODE||'',contentConfig:{mediaDir:process.env.MEDIA_DIR,publicBaseUrl:process.env.PUBLIC_BASE_URL||'',footballDataToken:process.env.FOOTBALL_DATA_API_KEY||'',pandaScoreToken:process.env.PANDASCORE_API_TOKEN||'',newsProvider:process.env.NEWS_PROVIDER||'gdelt',newsApiKey:process.env.NEWS_API_KEY||'',gdeltBaseUrl:process.env.GDELT_BASE_URL||undefined,mediaMaxTotalBytes:Number(process.env.MEDIA_MAX_TOTAL_BYTES)||undefined,mediaMaxFiles:Number(process.env.MEDIA_MAX_FILES)||undefined,newsRetentionMs:Number(process.env.NEWS_RETENTION_DAYS)*86400000||undefined,newsMaxArticles:Number(process.env.NEWS_MAX_ARTICLES)||undefined},aiConfig:{apiKey:process.env.AI_API_KEY||'',apiType:process.env.AI_API_TYPE||undefined,baseUrl:process.env.AI_BASE_URL||undefined,model:process.env.AI_MODEL||undefined,webSearchEnabled:process.env.AI_WEB_SEARCH_ENABLED!=='false',timeZone:process.env.APP_TIME_ZONE||'Asia/Shanghai',timeoutMs:Number(process.env.AI_TIMEOUT_MS)||undefined,rateLimitPerMinute:Number(process.env.AI_RATE_LIMIT_PER_MINUTE)||undefined}});app.server.listen(Number(process.env.PORT||8787),process.env.HOST||'127.0.0.1',()=>{console.log('API listening on port '+(process.env.PORT||8787));app.content.startScheduler({sportsIntervalMs:Number(process.env.SPORTS_SYNC_INTERVAL_MS)||900000,newsIntervalMs:Number(process.env.NEWS_SYNC_INTERVAL_MS)||3600000})});setInterval(()=>{try{app.tick()}catch(e){console.error('Scheduler failed')}},15000).unref()}
