import http from 'node:http';
import { DatabaseSync } from 'node:sqlite';
import { randomUUID, randomBytes, createHash } from 'node:crypto';
import { mkdirSync } from 'node:fs';
import { readFile } from 'node:fs/promises';
import { resolve, dirname, extname, sep } from 'node:path';
import { pathToFileURL } from 'node:url';
const fail=(status,message)=>{throw Object.assign(new Error(message),{status})};
const hash=v=>createHash('sha256').update(v).digest('hex');
export function createApp({dbPath='server/data/app.sqlite',testAuth=false,wxAppId='',wxSecret='',publicDir=''}={}){
 mkdirSync(dirname(resolve(dbPath)),{recursive:true});const db=new DatabaseSync(dbPath);
 db.exec(`PRAGMA journal_mode=WAL; CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY, identity TEXT UNIQUE,nickname TEXT,couple TEXT); CREATE TABLE IF NOT EXISTS sessions(token TEXT PRIMARY KEY,user TEXT,expires INTEGER); CREATE TABLE IF NOT EXISTS invites(code TEXT PRIMARY KEY,owner TEXT,expires INTEGER,used INTEGER DEFAULT 0); CREATE TABLE IF NOT EXISTS items(id TEXT PRIMARY KEY,owner TEXT,couple TEXT,kind TEXT,data TEXT); CREATE TABLE IF NOT EXISTS files(id TEXT PRIMARY KEY,owner TEXT,name TEXT,bytes BLOB); CREATE TABLE IF NOT EXISTS notifications(id TEXT PRIMARY KEY,user TEXT,title TEXT,due TEXT,seen INTEGER DEFAULT 0);`);
 const one=(s,...a)=>db.prepare(s).get(...a); const all=(s,...a)=>db.prepare(s).all(...a);const run=(s,...a)=>db.prepare(s).run(...a);
 const transaction=fn=>{db.exec('BEGIN IMMEDIATE');try{const r=fn();db.exec('COMMIT');return r}catch(e){db.exec('ROLLBACK');throw e}};
 const publicUser=u=>({id:u.id,nickname:u.nickname,partner:u.couple?all('SELECT id,nickname FROM users WHERE couple=? AND id<>?',u.couple,u.id)[0]||null:null});
 const publicRoot=publicDir?resolve(publicDir):'';const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8','.png':'image/png','.svg':'image/svg+xml','.ico':'image/x-icon','.woff2':'font/woff2'};
 async function servePublic(req,res,pathname){if(!publicRoot||!['GET','HEAD'].includes(req.method))return false;let decoded;try{decoded=decodeURIComponent(pathname)}catch{return false}const relative=(decoded==='/'?'index.html':decoded.replace(/^\/+/,''));let file=resolve(publicRoot,relative);if(file!==publicRoot&&!file.startsWith(publicRoot+sep))return false;try{let bytes=await readFile(file);res.writeHead(200,{'Content-Type':mime[extname(file).toLowerCase()]||'application/octet-stream','Cache-Control':extname(file)==='.html'?'no-cache':'public, max-age=31536000, immutable','X-Content-Type-Options':'nosniff','Referrer-Policy':'same-origin'});if(req.method==='HEAD')return res.end();res.end(bytes);return true}catch{if(extname(relative))return false;file=resolve(publicRoot,'index.html');try{const bytes=await readFile(file);res.writeHead(200,{'Content-Type':mime['.html'],'Cache-Control':'no-cache','X-Content-Type-Options':'nosniff','Referrer-Policy':'same-origin'});if(req.method==='HEAD')return res.end();res.end(bytes);return true}catch{return false}}}
 const session=identity=>{let u=one('SELECT * FROM users WHERE identity=?',identity);if(!u){const id=randomUUID();run('INSERT INTO users VALUES(?,?,?,NULL)',id,identity,identity.startsWith('test:')?identity.slice(5):'新朋友');u=one('SELECT * FROM users WHERE id=?',id)}const token=randomBytes(32).toString('hex');run('INSERT INTO sessions VALUES(?,?,?)',hash(token),u.id,Date.now()+30*864e5);return {token,user:publicUser(u)}};
 const visible=(item,u)=>item.owner===u.id||Boolean(item.couple&&item.couple===u.couple);
 function tick(now=Date.now()){
 transaction(()=>{for(const item of all("SELECT * FROM items WHERE kind='reminder'")){const d=JSON.parse(item.data);if(d.done||Date.parse(d.nextAt)-d.advance*60000>now)continue;const owner=one('SELECT * FROM users WHERE id=?',item.owner);const users=d.recipient==='me'?[owner]:all('SELECT * FROM users WHERE couple=?',item.couple).filter(u=>d.recipient==='both'||u.id!==owner.id);for(const u of users)run('INSERT OR IGNORE INTO notifications VALUES(?,?,?,?,0)',hash(item.id+':'+u.id+':'+d.nextAt),u.id,d.title,d.nextAt);if(d.repeat==='none')d.done=true;else{let next=Date.parse(d.nextAt);while(next-d.advance*60000<=now)next+=(d.repeat==='daily'?1:7)*864e5;d.nextAt=new Date(next).toISOString()}run('UPDATE items SET data=? WHERE id=?',JSON.stringify(d),item.id)}});
 }
 const server=http.createServer(async(req,res)=>{const send=(status,body)=>{res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff','Referrer-Policy':'same-origin'});res.end(JSON.stringify(body))};try{
 const url=new URL(req.url,'http://localhost');if(!url.pathname.startsWith('/api')){if(await servePublic(req,res,url.pathname))return;return send(404,{message:'页面不存在'})}const path=url.pathname.slice(4)||'/';
 let size=0;const chunks=[];for await(const chunk of req){size+=chunk.length;if(size>(path==='/files'?12:1)*1024*1024)fail(413,'内容超过大小限制');chunks.push(chunk)}let b={};if(size&&path!=='/files'){try{b=JSON.parse(Buffer.concat(chunks).toString())}catch{fail(400,'请求格式错误')}}
 if(path==='/health')return send(200,{ok:true});
 if(path==='/auth/test'&&req.method==='POST'){if(!testAuth)fail(404,'接口不存在');if(!['我','小金子','访客'].includes(b.name))fail(400,'无效测试账号');return send(200,session('test:'+b.name))}
 if(path==='/auth/wechat'&&req.method==='POST'){if(!wxAppId||!wxSecret)fail(503,'微信登录尚未配置');if(typeof b.code!=='string'||b.code.length>256)fail(400,'登录凭证无效');const query=new URLSearchParams({appid:wxAppId,secret:wxSecret,js_code:b.code,grant_type:'authorization_code'});const wx=await fetch('https://api.weixin.qq.com/sns/jscode2session?'+query,{signal:AbortSignal.timeout(10000)}).then(r=>r.json());if(!wx.openid)fail(401,'微信登录失败，请重试');return send(200,session('wx:'+wxAppId+':'+wx.openid))}
 const token=(req.headers.authorization||'').replace(/^Bearer /,'');const ses=one('SELECT * FROM sessions WHERE token=? AND expires>?',hash(token),Date.now());if(!ses)fail(401,'请先登录');const user=one('SELECT * FROM users WHERE id=?',ses.user);
 if(path==='/me'&&req.method==='GET')return send(200,publicUser(user));
 if(path==='/me'&&req.method==='PUT'){const nickname=String(b.nickname||'').trim();if(!nickname||nickname.length>20)fail(400,'昵称请填写 1—20 个字');run('UPDATE users SET nickname=? WHERE id=?',nickname,user.id);return send(200,publicUser(one('SELECT * FROM users WHERE id=?',user.id)))}
 if(path==='/logout'&&req.method==='POST'){run('DELETE FROM sessions WHERE token=?',hash(token));return send(200,{ok:true})}
 if(path==='/invite'&&req.method==='POST'){if(user.couple)fail(409,'已经绑定另一半');run('DELETE FROM invites WHERE owner=?',user.id);const code=randomBytes(6).toString('hex').toUpperCase();run('INSERT INTO invites VALUES(?,?,?,0)',code,user.id,Date.now()+864e5);return send(200,{code,expires:Date.now()+864e5})}
 const invite=()=>{const i=one('SELECT * FROM invites WHERE code=? AND used=0 AND expires>?',String(b.code||'').trim().toUpperCase(),Date.now());if(!i)fail(400,'邀请码无效或已过期');if(i.owner===user.id)fail(400,'不能邀请自己');const owner=one('SELECT * FROM users WHERE id=?',i.owner);if(owner.couple||user.couple)fail(409,'其中一方已经绑定');return {i,owner}};
 if(path==='/invite/preview'&&req.method==='POST'){const {owner}=invite();return send(200,{nickname:owner.nickname})}
 if(path==='/invite/accept'&&req.method==='POST'){transaction(()=>{const {i,owner}=invite();const c=randomUUID();run('UPDATE users SET couple=? WHERE id IN (?,?)',c,user.id,owner.id);run('UPDATE invites SET used=1 WHERE code=?',i.code)});return send(200,publicUser(one('SELECT * FROM users WHERE id=?',user.id)))}
 if(path==='/files'&&req.method==='POST'){if(!size)fail(400,'文件不能为空');const name=decodeURIComponent(req.headers['x-file-name']||'附件').slice(0,150);const total=one('SELECT COALESCE(SUM(length(bytes)),0) total FROM files WHERE owner=?',user.id).total;if(total+size>100*1024*1024)fail(413,'附件空间已满（100MB）');const id=randomUUID();run('INSERT INTO files VALUES(?,?,?,?)',id,user.id,name,Buffer.concat(chunks));return send(200,{id,name,size})}
 if(path.startsWith('/files/')&&req.method==='GET'){const file=one('SELECT * FROM files WHERE id=?',path.split('/')[2]);if(!file)fail(404,'文件不存在');const allowed=file.owner===user.id||all('SELECT * FROM items WHERE couple=?',user.couple).some(i=>JSON.parse(i.data).attachments?.some(a=>a.id===file.id));if(!allowed)fail(404,'文件不存在');res.writeHead(200,{'Content-Type':'application/octet-stream','Content-Disposition':"attachment; filename*=UTF-8''"+encodeURIComponent(file.name),'X-Content-Type-Options':'nosniff','Cache-Control':'no-store'});return res.end(Buffer.from(file.bytes))}
 if(path==='/items'&&req.method==='GET'){return send(200,all('SELECT * FROM items WHERE owner=? OR (couple IS NOT NULL AND couple=?)',user.id,user.couple).map(i=>({...JSON.parse(i.data),id:i.id,owner:i.owner,kind:i.kind,scope:i.couple?'shared':'mine'})))}
 if(path==='/items'&&req.method==='POST'||path.startsWith('/items/')&&req.method==='PUT'){
 let existing=null;const id=req.method==='PUT'?path.split('/')[2]:randomUUID();if(req.method==='PUT'){existing=one('SELECT * FROM items WHERE id=?',id);if(!existing||!visible(existing,user))fail(404,'内容不存在');if(existing.owner!==user.id&&b.scope==='mine')fail(403,'只有创建者可以改为私人内容')}
 const kind=existing?.kind||b.kind;if(!['note','reminder'].includes(kind))fail(400,'无效内容类型');const title=String(b.title||'').trim();if(!title||title.length>100)fail(400,'标题请填写 1—100 个字');if(!['mine','shared'].includes(b.scope))fail(400,'无效可见范围');if(b.scope==='shared'&&!user.couple)fail(400,'请先绑定另一半');const data={title,content:String(b.content||'').slice(0,50000),updatedAt:new Date().toISOString(),pinned:!!b.pinned,links:Array.isArray(b.links)?b.links.filter(x=>typeof x==='string'&&/^https?:\/\//i.test(x)).slice(0,20):[]};
 data.attachments=[];for(const a of (Array.isArray(b.attachments)?b.attachments:[]).slice(0,10)){const file=one('SELECT id,owner,name,length(bytes) size FROM files WHERE id=?',String(a.id));const old=existing?JSON.parse(existing.data).attachments||[]:[];if(!file||(file.owner!==user.id&&!old.some(x=>x.id===file.id)))fail(403,'无权引用此附件');data.attachments.push({id:file.id,name:file.name,size:file.size})}
 if(kind==='reminder'){if(!['none','daily','weekly'].includes(b.repeat)||!['me','partner','both'].includes(b.recipient))fail(400,'提醒规则无效');if(b.recipient!=='me'&&b.scope!=='shared')fail(400,'提醒另一半需要共享');const time=Date.parse(b.nextAt);if(!Number.isFinite(time))fail(400,'请选择提醒时间');if(!existing&&time<Date.now()-60000)fail(400,'提醒时间不能早于现在');Object.assign(data,{nextAt:new Date(time).toISOString(),repeat:b.repeat,recipient:b.recipient,advance:[0,15,30,60].includes(b.advance)?b.advance:0,done:!!b.done})}
 const owner=existing?.owner||user.id;run('INSERT INTO items VALUES(?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET couple=excluded.couple,data=excluded.data',id,owner,b.scope==='shared'?user.couple:null,kind,JSON.stringify(data));return send(200,{...data,id,owner,kind,scope:b.scope})}
 if(path.startsWith('/items/')&&req.method==='DELETE'){const i=one('SELECT * FROM items WHERE id=?',path.split('/')[2]);if(!i||!visible(i,user))fail(404,'内容不存在');if(i.owner!==user.id)fail(403,'只有创建者可以删除');run('DELETE FROM items WHERE id=?',i.id);return send(200,{ok:true})}
 if(path==='/notifications'&&req.method==='GET'){tick();return send(200,all('SELECT * FROM notifications WHERE user=? ORDER BY due DESC LIMIT 100',user.id))}
 if(path==='/notifications/read'&&req.method==='POST'){run('UPDATE notifications SET seen=1 WHERE user=?',user.id);return send(200,{ok:true})}
 fail(404,'接口不存在');
 }catch(e){send(e.status||500,{message:e.status?e.message:'服务暂时不可用，请稍后重试'})}});
 return {server,db,tick};
}
if(process.argv[1]&&import.meta.url===pathToFileURL(resolve(process.argv[1])).href){const app=createApp({dbPath:process.env.DB_PATH||'server/data/app.sqlite',wxAppId:process.env.WX_APP_ID,wxSecret:process.env.WX_APP_SECRET,publicDir:process.env.PUBLIC_DIR});app.server.listen(Number(process.env.PORT||8787),process.env.HOST||'127.0.0.1',()=>console.log('API listening on port '+(process.env.PORT||8787)));setInterval(()=>{try{app.tick()}catch(e){console.error('Scheduler failed')}},15000).unref()}
