import {test} from 'node:test';import assert from 'node:assert/strict';import {createHmac} from 'node:crypto';import {mkdir,mkdtemp,writeFile,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import {createApp,MAX_NOVEL_CONTENT_CHARACTERS} from './index.mjs';
import {DatabaseSync} from 'node:sqlite';
test('binding, private/shared access, attachments, due delivery',async()=>{
 const app=createApp({dbPath:':memory:',testAuth:true});await new Promise(r=>app.server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+app.server.address().port+'/api';
 const call=async(path,method='GET',data,token)=>{const r=await fetch(base+path,{method,headers:{'Content-Type':'application/json',Authorization:'Bearer '+(token||'')},body:data?JSON.stringify(data):undefined});return {status:r.status,...await r.json()}};
 try{
 const a=await call('/auth/test','POST',{name:'我'}),b=await call('/auth/test','POST',{name:'小金子'}),c=await call('/auth/test','POST',{name:'访客'});assert.ok(a.token);assert.equal(a.user.vip,true);
 const note=await call('/items','POST',{kind:'note',title:'私密',content:'only me',links:[],scope:'mine'},a.token);assert.ok(note.id);assert.equal((await call('/items/'+note.id,'PUT',{...note,title:'偷改'},b.token)).status,404);
 assert.equal((await call('/items/'+note.id,'GET',undefined,a.token)).title,'私密');assert.equal((await call('/items/'+note.id,'GET',undefined,b.token)).status,404);
 const noteShare=await call('/items/'+note.id+'/share','POST',{},a.token);assert.match(noteShare.token,/^[a-f0-9]{48}$/);const publicNote=await call('/shared/items/'+noteShare.token);assert.equal(publicNote.title,'私密');assert.equal(publicNote.content,'only me');assert.equal(publicNote.scope,'link');assert.deepEqual(publicNote.attachments,[]);assert.equal((await call('/shared/items/not-a-token')).status,404);
 const invitation=await call('/invite','POST',{},a.token);assert.equal((await call('/invites/'+invitation.code)).nickname,'我');assert.equal((await call('/invite/accept','POST',{code:invitation.code},a.token)).status,400);assert.equal((await call('/invite/preview','POST',{code:invitation.code},b.token)).nickname,'我');assert.equal((await call('/invite/accept','POST',{code:invitation.code},b.token)).partner.id,a.user.id);assert.equal((await call('/invites/'+invitation.code)).status,404);assert.equal((await call('/invite/accept','POST',{code:invitation.code},c.token)).status,400);
 assert.equal((await call('/items/'+note.id,'PUT',note,b.token)).status,404);
 const upload=await fetch(base+'/files',{method:'POST',headers:{Authorization:'Bearer '+a.token,'x-file-name':'example.txt'},body:'hello'}).then(r=>r.json());assert.ok(upload.id);assert.equal((await fetch(base+'/files/'+upload.id,{headers:{Authorization:'Bearer '+b.token}})).status,404);
 const multipart=new FormData();multipart.set('file',new Blob(['image-bytes'],{type:'image/jpeg'}),'photo.jpg');const multipartResponse=await fetch(base+'/files',{method:'POST',headers:{Authorization:'Bearer '+a.token,'x-file-name':encodeURIComponent('相册图片.jpg')},body:multipart});assert.equal(multipartResponse.status,200);const multipartUpload=await multipartResponse.json();assert.equal(multipartUpload.name,'相册图片.jpg');assert.equal(multipartUpload.size,11);assert.equal(await fetch(base+'/files/'+multipartUpload.id,{headers:{Authorization:'Bearer '+a.token}}).then(r=>r.text()),'image-bytes');
 const shared=await call('/items','POST',{kind:'note',title:'一起',content:'共享',links:[],attachments:[upload],scope:'shared'},a.token);assert.ok(shared.id);assert.equal((await fetch(base+'/files/'+upload.id,{headers:{Authorization:'Bearer '+b.token}})).status,200);assert.equal((await fetch(base+'/files/'+upload.id,{headers:{Authorization:'Bearer '+c.token}})).status,404);
 const paper=await call('/items','POST',{kind:'note',title:'灵感纸',content:'第一段\n买牛奶',links:['https://example.com'],attachments:[upload],scope:'mine',noteFormat:'paper',blocks:[{id:'p1',type:'paragraph',text:'第一段',style:{bold:true,align:'center',color:'#b04432'}},{id:'t1',type:'todo',text:'买牛奶',checked:true},{id:'i1',type:'image',attachmentId:upload.id},{id:'l1',type:'link',text:'示例',url:'https://example.com'},{id:'bad',type:'image',attachmentId:'missing'}]},a.token);assert.equal(paper.noteFormat,'paper');assert.equal(paper.blocks.length,4);assert.equal(paper.blocks[0].style.bold,true);assert.equal(paper.blocks.some(block=>block.attachmentId==='missing'),false);
 assert.equal((await call('/items/'+shared.id,'PUT',{...shared,title:'双方编辑'},b.token)).status,200);assert.equal((await call('/items/'+shared.id,'DELETE',undefined,b.token)).status,403);assert.equal((await call('/items/'+shared.id,'PUT',{...shared,scope:'mine'},b.token)).status,403);
 const due=new Date(Date.now()+1000).toISOString();const reminder=await call('/items','POST',{kind:'reminder',title:'买菜',content:'记得买番茄',scope:'shared',repeat:'none',recipient:'both',advance:0,nextAt:due,links:[]},a.token);assert.ok(reminder.id);const reminderShare=await call('/items/'+reminder.id+'/share','POST',{},b.token);const publicReminder=await call('/shared/items/'+reminderShare.token);assert.equal(publicReminder.kind,'reminder');assert.equal(publicReminder.title,'买菜');assert.equal(publicReminder.content,'记得买番茄');assert.equal(publicReminder.nextAt,due);const ownerSync=await call('/reminders/sync','GET',undefined,a.token),partnerSync=await call('/reminders/sync','GET',undefined,b.token),visitorSync=await call('/reminders/sync','GET',undefined,c.token);assert.equal(ownerSync.reminders[0].id,reminder.id);assert.equal(partnerSync.reminders[0].id,reminder.id);assert.equal(visitorSync.reminders.length,0);assert.match(partnerSync.reminders[0].route,/pages\/detail\/detail/);app.tick(Date.now()+2000);app.tick(Date.now()+2000);assert.equal(app.db.prepare('SELECT count(*) n FROM notifications').get().n,2);const notificationsBefore=await fetch(base+'/notifications',{headers:{Authorization:'Bearer '+a.token}}).then(r=>r.json());assert.equal(notificationsBefore[0].itemId,reminder.id);assert.equal(notificationsBefore[0].seen,0);await call('/notifications/read','POST',{itemId:reminder.id},a.token);const notificationsAfter=await fetch(base+'/notifications',{headers:{Authorization:'Bearer '+a.token}}).then(r=>r.json());assert.equal(notificationsAfter[0].seen,1);const partnerNotifications=await fetch(base+'/notifications',{headers:{Authorization:'Bearer '+b.token}}).then(r=>r.json());assert.equal(partnerNotifications[0].seen,0);
 const matchDue=new Date(Date.now()+86400000).toISOString();const matchPayload={kind:'reminder',title:'HOM vs AWY',content:'英超',scope:'mine',repeat:'none',recipient:'me',advance:30,nextAt:matchDue,links:[],sourceKey:'sports-match:football:101'};const matchReminder=await call('/items','POST',matchPayload,a.token);const sameMatchReminder=await call('/items','POST',{...matchPayload,content:'英超 · 时间更新',nextAt:new Date(Date.parse(matchDue)+3600000).toISOString()},a.token);assert.equal(sameMatchReminder.id,matchReminder.id);assert.equal(app.db.prepare("SELECT data FROM items WHERE owner=? AND kind='reminder'").all(a.user.id).filter(row=>JSON.parse(row.data).sourceKey==='sports-match:football:101').length,1);assert.match(sameMatchReminder.content,/时间更新/);const otherUserReminder=await call('/items','POST',matchPayload,b.token);assert.notEqual(otherUserReminder.id,matchReminder.id);await call('/items/'+matchReminder.id,'DELETE',undefined,a.token);const recreatedReminder=await call('/items','POST',matchPayload,a.token);assert.notEqual(recreatedReminder.id,matchReminder.id);
 const recurring=await call('/items','POST',{kind:'reminder',title:'散步',content:'',scope:'mine',repeat:'daily',recipient:'me',advance:0,nextAt:due,links:[]},a.token);app.tick(Date.now()+2000);const saved=JSON.parse(app.db.prepare('SELECT data FROM items WHERE id=?').get(recurring.id).data);assert.equal(saved.done,false);assert.ok(Date.parse(saved.nextAt)>Date.parse(due));
 assert.equal((await call('/items','POST',{kind:'note',title:'窃取附件',scope:'mine',attachments:[upload]},c.token)).status,403);
 await call('/items/'+note.id,'DELETE',undefined,a.token);assert.equal((await call('/shared/items/'+noteShare.token)).status,404);
 await call('/logout','POST',{},a.token);assert.equal((await call('/me','GET',undefined,a.token)).status,401);
 }finally{await new Promise(r=>app.server.close(r));app.db.close()}
});
test('deleting an item atomically clears dependants while preserving reusable authorizations and files',async()=>{
 const app=createApp({dbPath:':memory:',testAuth:true});await new Promise(r=>app.server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+app.server.address().port+'/api';
 const call=async(path,method='GET',data,token)=>{const response=await fetch(base+path,{method,headers:{'Content-Type':'application/json',Authorization:'Bearer '+(token||'')},body:data?JSON.stringify(data):undefined});return {status:response.status,...await response.json()}};
 const upload=async(token,name)=>fetch(base+'/files',{method:'POST',headers:{Authorization:'Bearer '+token,'x-file-name':encodeURIComponent(name)},body:Buffer.from(name)}).then(response=>response.json());
 try{
  const a=await call('/auth/test','POST',{name:'我'}),b=await call('/auth/test','POST',{name:'小金子'});
  const reused=await upload(a.token,'复用附件.png'),foreign=await upload(b.token,'对方附件.png');
  const first=await call('/items','POST',{kind:'note',title:'第一条',content:'',links:[],attachments:[reused],scope:'mine'},a.token);
  const second=await call('/items','POST',{kind:'note',title:'第二条',content:'',links:[],attachments:[reused],scope:'mine'},a.token);
  const textOnly=await call('/items','POST',{kind:'note',title:'正文 UUID',content:`正文里只是提到 ${reused.id}`,links:[],attachments:[],scope:'mine'},a.token);
  const firstData=JSON.parse(app.db.prepare('SELECT data FROM items WHERE id=?').get(first.id).data);firstData.attachments.push(foreign);app.db.prepare('UPDATE items SET data=? WHERE id=?').run(JSON.stringify(firstData),first.id);
  const secondData=JSON.parse(app.db.prepare('SELECT data FROM items WHERE id=?').get(second.id).data);secondData.attachments=[];secondData.blocks=[{id:'legacy-image',type:'image',attachmentId:reused.id}];app.db.prepare('UPDATE items SET data=? WHERE id=?').run(JSON.stringify(secondData),second.id);
  assert.equal((await call('/items/'+first.id,'DELETE',undefined,a.token)).status,200);
  assert.ok(app.db.prepare('SELECT id FROM files WHERE id=?').get(reused.id));
  assert.ok(app.db.prepare('SELECT id FROM files WHERE id=?').get(foreign.id));
  assert.equal((await call('/items/'+second.id,'DELETE',undefined,a.token)).status,200);
  assert.equal(app.db.prepare('SELECT id FROM files WHERE id=?').get(reused.id),undefined);
  assert.ok(app.db.prepare('SELECT id FROM items WHERE id=?').get(textOnly.id));
  assert.ok(app.db.prepare('SELECT id FROM files WHERE id=?').get(foreign.id));

  const owned=await upload(a.token,'提醒附件.png'),due=new Date(Date.now()+60000).toISOString();
  const reminder=await call('/items','POST',{kind:'reminder',title:'待删除提醒',content:'',links:[],attachments:[owned],scope:'mine',repeat:'none',recipient:'me',advance:0,nextAt:due},a.token);
  await call('/items/'+reminder.id+'/share','POST',{},a.token);
  app.db.prepare('INSERT INTO notifications(id,user,title,due,seen,item) VALUES(?,?,?,?,0,?)').run('delete-notification',a.user.id,'待删除提醒',due,reminder.id);
  app.db.prepare('INSERT INTO notifications(id,user,title,due,seen,item) VALUES(?,?,?,?,0,?)').run('delete-partner-notification',b.user.id,'待删除提醒',due,reminder.id);
  app.db.prepare('INSERT INTO wechat_reminder_subscriptions VALUES(?,?,?,?,?,?,?,?)').run('delete-pending',reminder.id,a.user.id,due,'pending',Date.now(),null,null);
  app.db.prepare('INSERT INTO wechat_reminder_subscriptions VALUES(?,?,?,?,?,?,?,?)').run('delete-sent',reminder.id,a.user.id,due,'sent',Date.now(),Date.now(),null);
  app.db.prepare('INSERT INTO wechat_reminder_subscriptions VALUES(?,?,?,?,?,?,?,?)').run('delete-sending',reminder.id,b.user.id,due,'sending',Date.now(),null,null);
  assert.equal((await call('/items/'+reminder.id+'/share','DELETE',undefined,a.token)).status,404);
  assert.ok(app.db.prepare('SELECT id FROM items WHERE id=?').get(reminder.id));
  app.db.exec(`CREATE TRIGGER reject_item_cleanup BEFORE DELETE ON items WHEN OLD.id='${reminder.id}' BEGIN SELECT RAISE(ABORT,'cleanup rollback'); END`);
  assert.equal((await call('/items/'+reminder.id,'DELETE',undefined,a.token)).status,500);
  assert.ok(app.db.prepare('SELECT id FROM items WHERE id=?').get(reminder.id));
  assert.ok(app.db.prepare('SELECT id FROM files WHERE id=?').get(owned.id));
  assert.equal(app.db.prepare('SELECT count(*) count FROM notifications WHERE item=?').get(reminder.id).count,2);
  assert.equal(app.db.prepare('SELECT count(*) count FROM item_shares WHERE item=?').get(reminder.id).count,1);
  assert.equal(app.db.prepare('SELECT count(*) count FROM wechat_reminder_subscriptions WHERE item=?').get(reminder.id).count,3);
  app.db.exec('DROP TRIGGER reject_item_cleanup');

  assert.equal((await call('/items/'+reminder.id,'DELETE',undefined,a.token)).status,200);
  assert.equal(app.db.prepare('SELECT id FROM items WHERE id=?').get(reminder.id),undefined);
  assert.equal(app.db.prepare('SELECT id FROM files WHERE id=?').get(owned.id),undefined);
  assert.equal(app.db.prepare('SELECT count(*) count FROM notifications WHERE item=?').get(reminder.id).count,0);
  assert.equal(app.db.prepare('SELECT count(*) count FROM item_shares WHERE item=?').get(reminder.id).count,0);
  assert.deepEqual({...app.db.prepare('SELECT item,due,status FROM wechat_reminder_subscriptions WHERE id=?').get('delete-pending')},{item:null,due:null,status:'pending'});
  assert.equal(app.db.prepare('SELECT id FROM wechat_reminder_subscriptions WHERE id=?').get('delete-sent'),undefined);
  assert.equal(app.db.prepare('SELECT id FROM wechat_reminder_subscriptions WHERE id=?').get('delete-sending'),undefined);

  const guarded=await upload(a.token,'损坏数据保护.png');const guardedItem=await call('/items','POST',{kind:'note',title:'损坏数据保护',content:'',links:[],attachments:[guarded],scope:'mine'},a.token);
  app.db.prepare('INSERT INTO items VALUES(?,?,NULL,?,?)').run('malformed-data-item',b.user.id,'note','{');
  assert.equal((await call('/items/'+guardedItem.id,'DELETE',undefined,a.token)).status,200);
  assert.ok(app.db.prepare('SELECT id FROM files WHERE id=?').get(guarded.id));
 }finally{await new Promise(r=>app.server.close(r));app.db.close()}
});
test('production does not expose test identities',async()=>{const app=createApp({dbPath:':memory:'});await new Promise(r=>app.server.listen(0,'127.0.0.1',r));try{const r=await fetch('http://127.0.0.1:'+app.server.address().port+'/api/auth/test',{method:'POST',body:JSON.stringify({name:'我'})});assert.equal(r.status,404)}finally{await new Promise(r=>app.server.close(r));app.db.close()}});
test('legacy user databases gain a disabled VIP flag without changing accounts',async()=>{const directory=await mkdtemp(join(tmpdir(),'together-notes-vip-')),dbPath=join(directory,'legacy.sqlite');const legacy=new DatabaseSync(dbPath);legacy.exec("CREATE TABLE users(id TEXT PRIMARY KEY, identity TEXT UNIQUE,nickname TEXT,couple TEXT); INSERT INTO users VALUES('legacy-user','app:legacy','旧账号',NULL)");legacy.close();const app=createApp({dbPath});try{const row=app.db.prepare('SELECT * FROM users WHERE id=?').get('legacy-user');assert.equal(row.nickname,'旧账号');assert.equal(row.vip,0)}finally{app.db.close();await rm(directory,{recursive:true,force:true})}});
test('legacy notifications gain reminder detail links',async()=>{const directory=await mkdtemp(join(tmpdir(),'together-notes-notifications-')),dbPath=join(directory,'legacy.sqlite');const legacy=new DatabaseSync(dbPath),due='2026-09-30T12:00:00.000Z';legacy.exec("CREATE TABLE users(id TEXT PRIMARY KEY,identity TEXT UNIQUE,nickname TEXT,couple TEXT); CREATE TABLE items(id TEXT PRIMARY KEY,owner TEXT,couple TEXT,kind TEXT,data TEXT); CREATE TABLE notifications(id TEXT PRIMARY KEY,user TEXT,title TEXT,due TEXT,seen INTEGER DEFAULT 0)");legacy.prepare('INSERT INTO users VALUES(?,?,?,NULL)').run('legacy-user','app:legacy','旧账号');legacy.prepare('INSERT INTO items VALUES(?,?,NULL,?,?)').run('legacy-reminder','legacy-user','reminder',JSON.stringify({title:'旧提醒',nextAt:due}));legacy.prepare('INSERT INTO notifications VALUES(?,?,?,?,0)').run('legacy-notification','legacy-user','旧提醒',due);legacy.close();const app=createApp({dbPath});try{assert.equal(app.db.prepare('SELECT item FROM notifications WHERE id=?').get('legacy-notification').item,'legacy-reminder')}finally{app.db.close();await rm(directory,{recursive:true,force:true})}});
test('app accounts register behind a beta code, log in securely, and can delete all owned data',async()=>{
 const app=createApp({dbPath:':memory:',appRegistrationCode:'private-beta-2026'});await new Promise(r=>app.server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+app.server.address().port+'/api';
 const call=async(path,method='GET',data,token)=>{const response=await fetch(base+path,{method,headers:{'Content-Type':'application/json',Authorization:'Bearer '+(token||'')},body:data?JSON.stringify(data):undefined});return {status:response.status,...await response.json()}};
 try{
  assert.equal((await call('/auth/app/status')).registrationEnabled,true);
  assert.equal((await call('/auth/app/register','POST',{username:'first_user',password:'safe-password-1',nickname:'我',acceptedTerms:true,betaCode:'wrong'})).status,403);
  assert.equal((await call('/auth/app/register','POST',{username:'me',password:'short',nickname:'我',acceptedTerms:true,betaCode:'private-beta-2026'})).status,400);
  const a=await call('/auth/app/register','POST',{username:'first_user',password:'safe-password-1',nickname:'我',acceptedTerms:true,betaCode:'private-beta-2026'});assert.equal(a.status,201);assert.ok(a.token);assert.equal(a.user.vip,false);
  assert.equal((await call('/auth/app/register','POST',{username:'FIRST_USER',password:'safe-password-2',nickname:'重复',acceptedTerms:true,betaCode:'private-beta-2026'})).status,409);
  assert.equal((await call('/auth/app/login','POST',{username:'first_user',password:'wrong-password'})).status,401);
  const loggedIn=await call('/auth/app/login','POST',{username:'FIRST_USER',password:'safe-password-1'});assert.equal(loggedIn.user.id,a.user.id);assert.equal(loggedIn.user.vip,false);app.db.prepare('UPDATE users SET vip=1 WHERE id=?').run(a.user.id);assert.equal((await call('/me','GET',undefined,a.token)).vip,true);assert.equal((await call('/me','PUT',{nickname:'我',vip:false},a.token)).vip,true);
  const credential=app.db.prepare('SELECT * FROM app_credentials WHERE user=?').get(a.user.id);assert.notEqual(credential.password_hash,'safe-password-1');assert.equal(credential.terms_version,'2026-09-23');
  const b=await call('/auth/app/register','POST',{username:'second_user',password:'safe-password-2',nickname:'小金子',acceptedTerms:true,betaCode:'private-beta-2026'});
  const invite=await call('/invite','POST',{},a.token);await call('/invite/accept','POST',{code:invite.code},b.token);
  const ownedByA=await call('/items','POST',{kind:'note',title:'随账号删除',content:'私人内容',links:[],scope:'shared'},a.token);
  const ownedByB=await call('/items','POST',{kind:'note',title:'保留给另一方',content:'解绑后转为私人',links:[],scope:'shared'},b.token);
  const accountDeleteDue=new Date(Date.now()+60000).toISOString();app.db.prepare('INSERT INTO notifications(id,user,title,due,seen,item) VALUES(?,?,?,?,0,?)').run('account-delete-partner-notification',b.user.id,'账号内容提醒',accountDeleteDue,ownedByA.id);
  assert.equal(app.db.prepare('SELECT count(*) count FROM notifications WHERE item=?').get(ownedByA.id).count,1);
  assert.equal((await call('/me','DELETE',{password:'wrong-password'},a.token)).status,403);
  assert.equal((await call('/me','DELETE',{password:'safe-password-1'},a.token)).status,200);
  assert.equal(app.db.prepare('SELECT count(*) count FROM notifications WHERE item=?').get(ownedByA.id).count,0);
  assert.equal((await call('/me','GET',undefined,a.token)).status,401);assert.equal((await call('/auth/app/login','POST',{username:'first_user',password:'safe-password-1'})).status,401);
  assert.equal((await call('/items/'+ownedByA.id,'GET',undefined,b.token)).status,404);
  const remaining=await call('/items/'+ownedByB.id,'GET',undefined,b.token);assert.equal(remaining.scope,'mine');assert.equal((await call('/me','GET',undefined,b.token)).partner,null);
 }finally{await new Promise(r=>app.server.close(r));app.db.close()}
});
test('app registration stays closed until a beta code is configured',async()=>{const app=createApp({dbPath:':memory:'});await new Promise(r=>app.server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+app.server.address().port+'/api';try{const status=await fetch(base+'/auth/app/status').then(r=>r.json());assert.equal(status.registrationEnabled,false);const response=await fetch(base+'/auth/app/register',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:'closed_user',password:'safe-password-1',nickname:'未开放',acceptedTerms:true,betaCode:'anything'})});assert.equal(response.status,503)}finally{await new Promise(r=>app.server.close(r));app.db.close()}});
test('an existing mini-program account can add App credentials without duplicating its data',async()=>{
 const app=createApp({dbPath:':memory:',testAuth:true});await new Promise(r=>app.server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+app.server.address().port+'/api';
 const call=async(path,method='GET',data,token)=>{const response=await fetch(base+path,{method,headers:{'Content-Type':'application/json',Authorization:'Bearer '+(token||'')},body:data?JSON.stringify(data):undefined});return {status:response.status,...await response.json()}};
 try{
  const mini=await call('/auth/test','POST',{name:'我'}),other=await call('/auth/test','POST',{name:'小金子'});const note=await call('/items','POST',{kind:'note',title:'原来的小记',content:'继续使用同一账号',links:[],scope:'mine'},mini.token);
  assert.deepEqual(await call('/me/app-credentials','GET',undefined,mini.token),{status:200,configured:false,username:null});
  assert.equal((await call('/me/app-credentials','PUT',{username:'bad',password:'short',acceptedTerms:true},mini.token)).status,400);
  const created=await call('/me/app-credentials','PUT',{username:'mini_owner',password:'safe-password-3',acceptedTerms:true},mini.token);assert.equal(created.status,200);assert.equal(created.username,'mini_owner');
  assert.equal((await call('/me/app-credentials','PUT',{username:'mini_owner',password:'safe-password-5',acceptedTerms:true},other.token)).status,409);
  const appLogin=await call('/auth/app/login','POST',{username:'MINI_OWNER',password:'safe-password-3'});assert.equal(appLogin.user.id,mini.user.id);assert.equal((await call('/items/'+note.id,'GET',undefined,appLogin.token)).title,'原来的小记');
  const updated=await call('/me/app-credentials','PUT',{username:'mini_owner_2',password:'safe-password-4',acceptedTerms:true},mini.token);assert.equal(updated.status,200);assert.equal((await call('/auth/app/login','POST',{username:'mini_owner',password:'safe-password-3'})).status,401);assert.equal((await call('/auth/app/login','POST',{username:'MINI_OWNER_2',password:'safe-password-4'})).user.id,mini.user.id);
  const credential=app.db.prepare('SELECT * FROM app_credentials WHERE user=?').get(mini.user.id);assert.notEqual(credential.password_hash,'safe-password-3');assert.equal(credential.terms_version,'2026-09-23');
 }finally{await new Promise(r=>app.server.close(r));app.db.close()}
});
test('production server can host the H5 build',async()=>{const dir=await mkdtemp(join(tmpdir(),'together-notes-'));await mkdir(join(dir,'app-updates'));await writeFile(join(dir,'index.html'),'<main>小记</main>');await writeFile(join(dir,'app.js'),'console.log("ok")');await writeFile(join(dir,'app-updates','latest.json'),'{}');await writeFile(join(dir,'app-updates','update.wgt'),'PK');const app=createApp({dbPath:':memory:',publicDir:dir});await new Promise(r=>app.server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+app.server.address().port;try{const home=await fetch(base+'/');assert.equal(home.status,200);assert.match(await home.text(),/小记/);const asset=await fetch(base+'/app.js');assert.equal(asset.headers.get('content-type'),'text/javascript; charset=utf-8');const latest=await fetch(base+'/app-updates/latest.json');assert.equal(latest.headers.get('cache-control'),'no-cache');const wgt=await fetch(base+'/app-updates/update.wgt');assert.match(wgt.headers.get('cache-control'),/immutable/);const fallback=await fetch(base+'/some/client/route');assert.equal(fallback.status,200);assert.match(await fallback.text(),/小记/)}finally{await new Promise(r=>app.server.close(r));app.db.close();await rm(dir,{recursive:true,force:true})}});
test('Stock Platform integration matches phone digests and creates one persistent reminder per day',async()=>{
 const app=createApp({dbPath:':memory:',testAuth:true,stockIntegrationToken:'shared-integration-secret'});await new Promise(r=>app.server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+app.server.address().port+'/api';
 const call=async(path,method='GET',data,token)=>{const response=await fetch(base+path,{method,headers:{'Content-Type':'application/json',Authorization:'Bearer '+(token||'')},body:data?JSON.stringify(data):undefined});return {status:response.status,...await response.json()}};
 try{
  const account=await call('/auth/test','POST',{name:'我'});assert.equal((await call('/me/phone','GET',undefined,account.token)).configured,false);assert.equal((await call('/me/phone','PUT',{phone:'13800138000'},account.token)).masked,'*******8000');
  const phoneHash=createHmac('sha256','shared-integration-secret').update('13800138000').digest('hex');
  assert.equal((await call('/integrations/stock-platform/link-status','POST',{phone_hash:phoneHash},'wrong')).status,401);
  assert.equal((await call('/integrations/stock-platform/link-status','POST',{phone_hash:phoneHash},'shared-integration-secret')).linked,true);
  const reminder={phone_hash:phoneHash,source_key:'stock-platform:daily:2026-09-23',title:'当日股票推荐',content:'1. 示例股票（600001）｜+3.25%\n推荐模型：均衡观察\n观察依据：成交活跃',delivered_at:'2026-09-23T16:00:00+08:00'};
  const initial=await call('/integrations/stock-platform/reminders','POST',{...reminder,source_key:'stock-platform:initial:2026-09-23',delivered_at:'2026-09-23T09:35:00+08:00'},'shared-integration-secret');
  const first=await call('/integrations/stock-platform/reminders','POST',reminder,'shared-integration-secret'),second=await call('/integrations/stock-platform/reminders','POST',reminder,'shared-integration-secret');assert.equal(initial.status,201);assert.equal(first.status,201);assert.equal(second.status,200);assert.equal(second.id,first.id);assert.notEqual(initial.id,first.id);
  const stored=app.db.prepare("SELECT id,data FROM items WHERE owner=? AND kind='reminder'").all(account.user.id).filter(item=>JSON.parse(item.data).sourceKey===reminder.source_key);assert.equal(stored.length,1);assert.equal(JSON.parse(stored[0].data).done,false);app.tick(Date.parse('2026-09-24T00:00:00Z'));assert.equal(JSON.parse(app.db.prepare('SELECT data FROM items WHERE id=?').get(first.id).data).done,false);assert.equal(app.db.prepare('SELECT count(*) count FROM notifications').get().count,2);
  const resent=await call('/integrations/stock-platform/reminders','POST',{...reminder,delivered_at:'2026-09-23T16:10:00+08:00',notify_again:true},'shared-integration-secret');assert.equal(resent.id,first.id);assert.equal(app.db.prepare('SELECT count(*) count FROM notifications').get().count,3);
 }finally{await new Promise(r=>app.server.close(r));app.db.close()}
});
test('operations API protects account data, manages VIP, and scopes novels to selected VIP users',async()=>{
 const app=createApp({dbPath:':memory:',testAuth:true,opsAdminToken:'operations-secret'});await new Promise(r=>app.server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+app.server.address().port+'/api';
 const call=async(path,method='GET',data,token)=>{const response=await fetch(base+path,{method,headers:{'Content-Type':'application/json',Authorization:'Bearer '+(token||'')},body:data?JSON.stringify(data):undefined});return {status:response.status,...await response.json()}};
 try{
  const account=await call('/auth/test','POST',{name:'我'}),other=await call('/auth/test','POST',{name:'小金子'});assert.equal((await call('/operations/summary','GET',undefined,'wrong-token')).status,401);
  const summary=await call('/operations/summary','GET',undefined,'operations-secret');assert.equal(summary.accounts,2);assert.equal(summary.vipAccounts,2);
  const users=await call('/operations/users?q=%E6%88%91','GET',undefined,'operations-secret');assert.equal(users.total,1);assert.equal(users.items[0].nickname,'我');
  const disabled=await call(`/operations/users/${account.user.id}/vip`,'PUT',{enabled:false},'operations-secret');assert.equal(disabled.vip,false);assert.equal((await call('/novels','GET',undefined,account.token)).status,403);
  const enabled=await call(`/operations/users/${account.user.id}/vip`,'PUT',{enabled:true,expires_at:new Date(Date.now()+86400000).toISOString()},'operations-secret');assert.equal(enabled.vip,true);assert.ok(enabled.vipExpiresAt);
  const uploaded=await call('/operations/novels','POST',{title:'测试小说',author:'作者',filename:'test.txt',content:'第一章\n\n这是正文。',audience:'selected',userIds:[account.user.id]},'operations-secret');assert.equal(uploaded.status,201);assert.equal(uploaded.character_count,10);assert.equal(uploaded.audience,'selected');assert.equal(uploaded.allowedUserCount,1);
  const oversized=await call('/operations/novels','POST',{title:'超长小说',filename:'large.txt',content:'a'.repeat(MAX_NOVEL_CONTENT_CHARACTERS+1),audience:'all_vip'},'operations-secret');assert.equal(oversized.status,413);assert.equal(oversized.message,'单本内容不能超过 500 万字');
  const novels=await call('/novels','GET',undefined,account.token);assert.equal(novels.items.length,1);const catalog=await call('/novels/'+uploaded.id+'/chapters','GET',undefined,account.token);assert.equal(catalog.chapterCount,1);assert.equal(catalog.chapters[0].title,'第一章');assert.equal('content' in catalog.chapters[0],false);const chapter=await call('/novels/'+uploaded.id+'/chapters/0','GET',undefined,account.token);assert.equal(chapter.content,'这是正文。');const novel=await call('/novels/'+uploaded.id,'GET',undefined,account.token);assert.equal(novel.content,'第一章\n\n这是正文。');
  assert.equal((await call('/novels','GET',undefined,other.token)).items.length,0);assert.equal((await call('/novels/'+uploaded.id,'GET',undefined,other.token)).status,404);assert.equal((await call('/novels/'+uploaded.id+'/chapters','GET',undefined,other.token)).status,404);
  assert.equal((await call('/operations/novels/'+uploaded.id,'DELETE',undefined,'operations-secret')).ok,true);assert.equal((await call('/novels/'+uploaded.id,'GET',undefined,account.token)).status,404);assert.equal(app.db.prepare('SELECT count(*) count FROM novel_chapters WHERE novel=?').get(uploaded.id).count,0);
 }finally{await new Promise(r=>app.server.close(r));app.db.close()}
});
