import {test} from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,writeFile,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import {createApp} from './index.mjs';
test('binding, private/shared access, attachments, due delivery',async()=>{
 const app=createApp({dbPath:':memory:',testAuth:true});await new Promise(r=>app.server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+app.server.address().port+'/api';
 const call=async(path,method='GET',data,token)=>{const r=await fetch(base+path,{method,headers:{'Content-Type':'application/json',Authorization:'Bearer '+(token||'')},body:data?JSON.stringify(data):undefined});return {status:r.status,...await r.json()}};
 try{
 const a=await call('/auth/test','POST',{name:'我'}),b=await call('/auth/test','POST',{name:'小金子'}),c=await call('/auth/test','POST',{name:'访客'});assert.ok(a.token);
 const note=await call('/items','POST',{kind:'note',title:'私密',content:'only me',links:[],scope:'mine'},a.token);assert.ok(note.id);assert.equal((await call('/items/'+note.id,'PUT',{...note,title:'偷改'},b.token)).status,404);
 assert.equal((await call('/items/'+note.id,'GET',undefined,a.token)).title,'私密');assert.equal((await call('/items/'+note.id,'GET',undefined,b.token)).status,404);
 const noteShare=await call('/items/'+note.id+'/share','POST',{},a.token);assert.match(noteShare.token,/^[a-f0-9]{48}$/);const publicNote=await call('/shared/items/'+noteShare.token);assert.equal(publicNote.title,'私密');assert.equal(publicNote.content,'only me');assert.equal(publicNote.scope,'link');assert.deepEqual(publicNote.attachments,[]);assert.equal((await call('/shared/items/not-a-token')).status,404);
 const invitation=await call('/invite','POST',{},a.token);assert.equal((await call('/invites/'+invitation.code)).nickname,'我');assert.equal((await call('/invite/accept','POST',{code:invitation.code},a.token)).status,400);assert.equal((await call('/invite/preview','POST',{code:invitation.code},b.token)).nickname,'我');assert.equal((await call('/invite/accept','POST',{code:invitation.code},b.token)).partner.id,a.user.id);assert.equal((await call('/invites/'+invitation.code)).status,404);assert.equal((await call('/invite/accept','POST',{code:invitation.code},c.token)).status,400);
 assert.equal((await call('/items/'+note.id,'PUT',note,b.token)).status,404);
 const upload=await fetch(base+'/files',{method:'POST',headers:{Authorization:'Bearer '+a.token,'x-file-name':'example.txt'},body:'hello'}).then(r=>r.json());assert.ok(upload.id);assert.equal((await fetch(base+'/files/'+upload.id,{headers:{Authorization:'Bearer '+b.token}})).status,404);
 const shared=await call('/items','POST',{kind:'note',title:'一起',content:'共享',links:[],attachments:[upload],scope:'shared'},a.token);assert.ok(shared.id);assert.equal((await fetch(base+'/files/'+upload.id,{headers:{Authorization:'Bearer '+b.token}})).status,200);assert.equal((await fetch(base+'/files/'+upload.id,{headers:{Authorization:'Bearer '+c.token}})).status,404);
 assert.equal((await call('/items/'+shared.id,'PUT',{...shared,title:'双方编辑'},b.token)).status,200);assert.equal((await call('/items/'+shared.id,'DELETE',undefined,b.token)).status,403);assert.equal((await call('/items/'+shared.id,'PUT',{...shared,scope:'mine'},b.token)).status,403);
 const due=new Date(Date.now()+1000).toISOString();const reminder=await call('/items','POST',{kind:'reminder',title:'买菜',content:'记得买番茄',scope:'shared',repeat:'none',recipient:'both',advance:0,nextAt:due,links:[]},a.token);assert.ok(reminder.id);const reminderShare=await call('/items/'+reminder.id+'/share','POST',{},b.token);const publicReminder=await call('/shared/items/'+reminderShare.token);assert.equal(publicReminder.kind,'reminder');assert.equal(publicReminder.title,'买菜');assert.equal(publicReminder.content,'记得买番茄');assert.equal(publicReminder.nextAt,due);app.tick(Date.now()+2000);app.tick(Date.now()+2000);assert.equal(app.db.prepare('SELECT count(*) n FROM notifications').get().n,2);
 const matchDue=new Date(Date.now()+86400000).toISOString();const matchPayload={kind:'reminder',title:'HOM vs AWY',content:'英超',scope:'mine',repeat:'none',recipient:'me',advance:30,nextAt:matchDue,links:[],sourceKey:'sports-match:football:101'};const matchReminder=await call('/items','POST',matchPayload,a.token);const sameMatchReminder=await call('/items','POST',{...matchPayload,content:'英超 · 时间更新',nextAt:new Date(Date.parse(matchDue)+3600000).toISOString()},a.token);assert.equal(sameMatchReminder.id,matchReminder.id);assert.equal(app.db.prepare("SELECT data FROM items WHERE owner=? AND kind='reminder'").all(a.user.id).filter(row=>JSON.parse(row.data).sourceKey==='sports-match:football:101').length,1);assert.match(sameMatchReminder.content,/时间更新/);const otherUserReminder=await call('/items','POST',matchPayload,b.token);assert.notEqual(otherUserReminder.id,matchReminder.id);await call('/items/'+matchReminder.id,'DELETE',undefined,a.token);const recreatedReminder=await call('/items','POST',matchPayload,a.token);assert.notEqual(recreatedReminder.id,matchReminder.id);
 const recurring=await call('/items','POST',{kind:'reminder',title:'散步',content:'',scope:'mine',repeat:'daily',recipient:'me',advance:0,nextAt:due,links:[]},a.token);app.tick(Date.now()+2000);const saved=JSON.parse(app.db.prepare('SELECT data FROM items WHERE id=?').get(recurring.id).data);assert.equal(saved.done,false);assert.ok(Date.parse(saved.nextAt)>Date.parse(due));
 assert.equal((await call('/items','POST',{kind:'note',title:'窃取附件',scope:'mine',attachments:[upload]},c.token)).status,403);
 await call('/items/'+note.id,'DELETE',undefined,a.token);assert.equal((await call('/shared/items/'+noteShare.token)).status,404);
 await call('/logout','POST',{},a.token);assert.equal((await call('/me','GET',undefined,a.token)).status,401);
 }finally{await new Promise(r=>app.server.close(r));app.db.close()}
});
test('production does not expose test identities',async()=>{const app=createApp({dbPath:':memory:'});await new Promise(r=>app.server.listen(0,'127.0.0.1',r));try{const r=await fetch('http://127.0.0.1:'+app.server.address().port+'/api/auth/test',{method:'POST',body:JSON.stringify({name:'我'})});assert.equal(r.status,404)}finally{await new Promise(r=>app.server.close(r));app.db.close()}});
test('production server can host the H5 build',async()=>{const dir=await mkdtemp(join(tmpdir(),'together-notes-'));await writeFile(join(dir,'index.html'),'<main>小记</main>');await writeFile(join(dir,'app.js'),'console.log("ok")');const app=createApp({dbPath:':memory:',publicDir:dir});await new Promise(r=>app.server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+app.server.address().port;try{const home=await fetch(base+'/');assert.equal(home.status,200);assert.match(await home.text(),/小记/);const asset=await fetch(base+'/app.js');assert.equal(asset.headers.get('content-type'),'text/javascript; charset=utf-8');const fallback=await fetch(base+'/some/client/route');assert.equal(fallback.status,200);assert.match(await fallback.text(),/小记/)}finally{await new Promise(r=>app.server.close(r));app.db.close();await rm(dir,{recursive:true,force:true})}});
